baseURL = "https://animewall.my.id/"
languageCode = "en-us"
title = "animewall.my.id"
theme = "hugo-theme-gallery"

# SEO Meta Information
[params]
  description = "Discover and download free HD and 4K wallpapers anime for all devices at animewall. Stunning collection for your phone"
  search_description = "Discover and download free HD wallpapers anime for your devices at animewall. Stunning collection for your android or iphone."
  keywords = ["wallpaper", "wallpapers", "anime wallpaper", "android wallpaper", "phone wallpaper", "iphone wallpaper", "hd wallpaper", "download wallpaper", "animewall.my.id"]
  ogImage = "/images/default-og-image.jpg"
  [author]
    name = "animewall"
    twitter = "@animewall"
    copyright = "© 2024 animewall.my.id"
    language = "English"

# Open Graph / Social Media Meta Tags
[params.social]
  twitter_card = "summary_large_image"
  twitter_creator = "@animewall"
  twitter_site = "@animewall"
  og_title = "animewall"
  og_description = "Discover and download free HD and 4K wallpapers anime for all devices at animewall. Stunning collection for your phone"
  og_image = "/images/default-og-image.jpg"
  og_url = "https://animewall.my.id/"

# SEO Schema Markup
[params.schema]
  type = "WebSite"
  name = "animewall.my.id"
  url = "https://animewall.my.id/"
  image = "/images/default-og-image.jpg"
  description = "Discover and download free HD and 4K wallpapers anime for all devices at animewall. Stunning collection for your phone"
  keywords = ["wallpaper", "wallpapers", "anime wallpaper", "android wallpaper", "phone wallpaper", "iphone wallpaper", "hd wallpaper", "download wallpaper", "animewall.my.id"]

# Google Analytics (Optional)
[params.googleAnalytics]
  trackingID = ""

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[outputs]
  home = ["HTML", "RSS", "Sitemap"]
  page = ["HTML"]
  section = ["HTML"]
[sitemap]
changefreq = "daily"
priority = 0.5
filename = "sitemap.xml"
