baseURL = "https://wallpaper.cyou/"
languageCode = "en-us"
title = "Free HD Wallpaper Downloads - Wallpaper.cyou"
theme = "hugo-theme-gallery"

# SEO Meta Information
[params]
  description = "Free HD wallpaper for download. Explore stunning 4K and HD wallpapers on Wallpaper.cyou."
  search_description = "Discover and download free HD and 4K wallpapers for all devices at Wallpaper.cyou."
  keywords = ["wallpaper", "wallpapers", "8k wallpaper", "4k wallpaper", "phone wallpaper", "HD wallpaper", "free wallpaper", "download wallpaper", "wallpaper.cyou"]
  ogImage = "/images/default-og-image.jpg"
  [author]
    name = "Wallpaper Cyou"
    twitter = "@WallpaperCyou"
    copyright = "© 2024 Wallpaper.cyou"
    language = "English"

# Open Graph / Social Media Meta Tags
[params.social]
  twitter_card = "summary_large_image"
  twitter_creator = "@wallpapercyou"
  twitter_site = "@wallpapercyou"
  og_title = "Free HD Wallpaper Downloads - Wallpaper.cyou"
  og_description = "Free HD wallpaper for download. Explore stunning 4K and HD wallpapers on Wallpaper.cyou."
  og_image = "/images/default-og-image.jpg"
  og_url = "https://wallpaper.cyou/"

# SEO Schema Markup
[params.schema]
  type = "WebSite"
  name = "Wallpaper.cyou"
  url = "https://wallpaper.cyou/"
  image = "/images/default-og-image.jpg"
  description = "Free HD wallpaper for download. Explore stunning 4K and HD wallpapers on Wallpaper.cyou."
  keywords = ["wallpaper", "wallpapers", "HD wallpaper", "4k wallpaper", "phone wallpaper"]

# Google Analytics (Optional)
[params.googleAnalytics]
  trackingID = "G-VRHG2FF2GG"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[outputs]
  home = ["HTML", "RSS", "Sitemap"]
  page = ["HTML"]
  section = ["HTML"]
